### ISSUE TITLE
utils.check_uvd_pair_metadata always fails for Ntimes=1

### ISSUE THREAD

**Issue by Jackmastr** [HERA-Team/uvtools#60]
A ` MetadataError: "Time values disagree more than the mean integration time."` is thrown even when identical UVData objects are passed to the function.

Starting at line 181 in utils.py:
```python
dx = lambda x1, x2 : 0.5 * (np.mean(np.diff(x1)) + np.mean(np.diff(x2)))

t1vals = np.unique(uvd1.time_array)
t2vals = np.unique(uvd2.time_array)
if not np.all(
    np.isclose(t1vals, t2vals, rtol=0, atol=dx(t1vals, t2vals))
):
    raise MetadataError(
        "Time values disagree more than the mean integration time."
    )
```

if `uvd1` and `uvd2` only contain one unique time then the expression `dx(t1vals, t2vals)` always returns `nan`. [np.diff](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html) returns an empty array when passed an array with one element, and [np.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html) returns nan when passed an empty array.

**Comment by Jackmastr** [comment]
Additionally, `plot.plot_diff_waterfall` (and potentially other functions) seems to fail (`ValueError: Axis limits cannot be NaN or Inf`) for UVData that have only one unique time if their `check_metadata` parameter is set to False.

**Comment by r-pascua** [comment]
The first problem should be relatively straightforward to fix. I'm not sure if it's worth adding handling for the second issue, since it doesn't make sense to make a waterfall plot for an array with shape `(N, 1)`. Either way, I'll make a point to add some more tests to make sure that things don't break when they shouldn't for the difference plotting routines. Thanks for providing a succinct summary of the issue!
