### ISSUE TITLE
Break up uvtools into pipeline code and utility code

### ISSUE THREAD

**Issue by anguta** [HERA-Team/uvtools#90]
`uvtools` contains code that contributes to the HERA pipeline (primarily `dspec.py`) along with number of other libraries that are useful analysis utilities but are not core to the analysis pipeline. Since pipeline code is held to a very high standard that may not be necessary for utility code, it could make sense to break `uvtools` up into pipeline essential and accessory code.

**Comment by jsdillon** [comment]
One place the plotting code could go is in `hera_notebook_templates`...

**Comment by r-pascua** [comment]
This sounds like it might soon be time for a code review and repo clean/refactorization. It looks like significant chunks of under-covered code is stuff that's a few years old with minimal documentation, and it seems likely that there might not be any people who even use that code anymore.

I think I support the spirit of this, though I don't think it's time to make it a priority&mdash;maybe once the observing season is running along nicely we can divert some people power to making this happen. I can get behind putting plotting code in a separate repo, either `hera_notebook_templates` as @jsdillon suggests, or perhaps a new `uvplot` repo; however, I don't like the idea of not testing plotting code. There are at least a set of sanity checks that one can do, and, depending on how deeply they want to dig into all the objects that go into a `matplotlib.Figure` object, more rigorous tests that can be done.

As for things I'd like to see if something like this were to happen in the future, there are two main changes: first, if we're going to start holding some of this code to higher standards, then I think we need (or should be strongly incentivized) to add black/flake8/pre-commit infrastructure, since this helps with both style consistency and hard-to-find bugfixes; second, if we're holding the repo to a higher standard of testing (contrasted with coverage), then I think we need to make the tests reflect that as well, in the sense of them being more atomized, easier to read, and preferentially written using only `pytest`.

I would be interested to hear what @dannyjacobs has to say.

**Comment by anguta** [comment]
@jsdillon @nkern  what modules from `uvtools` does the pipeline currently use?

**Comment by jsdillon** [comment]
I think just dspec. 

Honestly, I think the best course is to keep the repo together, but to move old code into a submodule (`uvtools.old` or something) that isn't part of the continuous integration. Perhaps we can have that code issue a warning every time its imported. 

I'd also be OK moving it back to hera_sandbox if truly no one is using it...
